server:
  port: 8080

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

user:
  role:
    default-name: "USER"

jwt:
  access:
    secret: "fL6pW9zYvN4uX2bQ8mK0jH5gD1sA7rE3tZ6xV9cM2nB4="
    expiration: 120000
  refresh:
    secret: "G8hJ2kL5mN7pQ9rS1tU3vW5xY7zA2bC4dE6fG8hJ0kL="
    expiration: 3600000